// ignore_for_file: camel_case_types, non_constant_identifier_names

// Manually maintained bindings for RARHeaderDataEx and RAROpenArchiveDataEx.
//
// These structs could not be auto-generated by ffigen because they contain
// wchar_t arrays whose element size is platform-specific:
//   - macOS / Linux (Unix): wchar_t = 4 bytes (Uint32)
//   - Windows:              wchar_t = 2 bytes (Uint16)
//
// This file targets Unix (macOS and Linux). The struct layouts below use
// Uint32 for wchar_t fields and are verified against dll.hpp with
// #pragma pack(1) applied.
//
// Total size of RARHeaderDataEx on macOS/Linux: 14412 bytes.
// Total size of RAROpenArchiveDataEx on macOS/Linux: 136 bytes.

import 'dart:ffi' as ffi;
import 'unrar_bindings.dart' as b;

/// Extended archive header data — 1024-char filenames, 64-bit sizes,
/// Blake2 hash support, and per-entry timestamp precision.
///
/// Layout (Unix, wchar_t = 4 bytes, #pragma pack(1)):
///   [0]      ArcName[1024]        char[1024]
///   [1024]   ArcNameW[1024]       wchar_t[1024] = Uint32[1024] = 4096 bytes
///   [5120]   FileName[1024]       char[1024]
///   [6144]   FileNameW[1024]      wchar_t[1024] = Uint32[1024] = 4096 bytes
///   [10240]  Flags                unsigned int
///   [10244]  PackSize             unsigned int
///   [10248]  PackSizeHigh         unsigned int
///   [10252]  UnpSize              unsigned int
///   [10256]  UnpSizeHigh          unsigned int
///   [10260]  HostOS               unsigned int
///   [10264]  FileCRC              unsigned int
///   [10268]  FileTime             unsigned int
///   [10272]  UnpVer               unsigned int
///   [10276]  Method               unsigned int
///   [10280]  FileAttr             unsigned int
///   [10284]  CmtBuf*              pointer (8 bytes)
///   [10292]  CmtBufSize           unsigned int
///   [10296]  CmtSize              unsigned int
///   [10300]  CmtState             unsigned int
///   [10304]  DictSize             unsigned int
///   [10308]  HashType             unsigned int
///   [10312]  Hash[32]             char[32]
///   [10344]  RedirType            unsigned int
///   [10348]  RedirName*           pointer (8 bytes)
///   [10356]  RedirNameSize        unsigned int
///   [10360]  DirTarget            unsigned int
///   [10364]  MtimeLow             unsigned int
///   [10368]  MtimeHigh            unsigned int
///   [10372]  CtimeLow             unsigned int
///   [10376]  CtimeHigh            unsigned int
///   [10380]  AtimeLow             unsigned int
///   [10384]  AtimeHigh            unsigned int
///   [10388]  ArcNameEx*           pointer (8 bytes)
///   [10396]  ArcNameExSize        unsigned int
///   [10400]  FileNameEx*          pointer (8 bytes)
///   [10408]  FileNameExSize       unsigned int
///   [10412]  Reserved[982]        unsigned int[982] = 3928 bytes
///   Total = 14340 bytes
@ffi.Packed(1)
final class RARHeaderDataEx extends ffi.Struct {
  @ffi.Array.multi([1024])
  external ffi.Array<ffi.Char> ArcName;

  // wchar_t ArcNameW[1024] — 4 bytes per element on Unix
  @ffi.Array.multi([1024])
  external ffi.Array<ffi.Uint32> ArcNameW;

  @ffi.Array.multi([1024])
  external ffi.Array<ffi.Char> FileName;

  // wchar_t FileNameW[1024] — 4 bytes per element on Unix
  @ffi.Array.multi([1024])
  external ffi.Array<ffi.Uint32> FileNameW;

  @ffi.UnsignedInt()
  external int Flags;

  @ffi.UnsignedInt()
  external int PackSize;

  @ffi.UnsignedInt()
  external int PackSizeHigh;

  @ffi.UnsignedInt()
  external int UnpSize;

  @ffi.UnsignedInt()
  external int UnpSizeHigh;

  @ffi.UnsignedInt()
  external int HostOS;

  @ffi.UnsignedInt()
  external int FileCRC;

  @ffi.UnsignedInt()
  external int FileTime;

  @ffi.UnsignedInt()
  external int UnpVer;

  @ffi.UnsignedInt()
  external int Method;

  @ffi.UnsignedInt()
  external int FileAttr;

  external ffi.Pointer<ffi.Char> CmtBuf;

  @ffi.UnsignedInt()
  external int CmtBufSize;

  @ffi.UnsignedInt()
  external int CmtSize;

  @ffi.UnsignedInt()
  external int CmtState;

  @ffi.UnsignedInt()
  external int DictSize;

  /// Hash algorithm: 0=none, 1=CRC32, 2=Blake2.
  @ffi.UnsignedInt()
  external int HashType;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> Hash;

  @ffi.UnsignedInt()
  external int RedirType;

  // wchar_t *RedirName — accessed as void* since we don't dereference it
  external ffi.Pointer<ffi.Void> RedirName;

  @ffi.UnsignedInt()
  external int RedirNameSize;

  @ffi.UnsignedInt()
  external int DirTarget;

  @ffi.UnsignedInt()
  external int MtimeLow;

  @ffi.UnsignedInt()
  external int MtimeHigh;

  @ffi.UnsignedInt()
  external int CtimeLow;

  @ffi.UnsignedInt()
  external int CtimeHigh;

  @ffi.UnsignedInt()
  external int AtimeLow;

  @ffi.UnsignedInt()
  external int AtimeHigh;

  // wchar_t *ArcNameEx
  external ffi.Pointer<ffi.Void> ArcNameEx;

  @ffi.UnsignedInt()
  external int ArcNameExSize;

  // wchar_t *FileNameEx
  external ffi.Pointer<ffi.Void> FileNameEx;

  @ffi.UnsignedInt()
  external int FileNameExSize;

  @ffi.Array.multi([982])
  external ffi.Array<ffi.Uint32> Reserved;
}

/// Extended archive open data — Unicode archive paths and archive-level flags.
///
/// Layout (Unix, wchar_t = 4 bytes, #pragma pack(1)):
///   [0]   ArcName*         pointer (8 bytes)
///   [8]   ArcNameW*        pointer (8 bytes)
///   [16]  OpenMode         unsigned int
///   [20]  OpenResult       unsigned int
///   [24]  CmtBuf*          pointer (8 bytes)
///   [32]  CmtBufSize       unsigned int
///   [36]  CmtSize          unsigned int
///   [40]  CmtState         unsigned int
///   [44]  Flags            unsigned int  ← ROADF_* bits populated after open
///   [48]  Callback         function pointer (8 bytes)
///   [56]  UserData         long (8 bytes on 64-bit Unix)
///   [64]  OpFlags          unsigned int  ← set ROADOF_KEEPBROKEN here
///   [68]  CmtBufW*         pointer (8 bytes)
///   [76]  MarkOfTheWeb*    pointer (8 bytes)
///   [84]  Reserved[23]     unsigned int[23] = 92 bytes
///   Total = 176 bytes
@ffi.Packed(1)
final class RAROpenArchiveDataEx extends ffi.Struct {
  external ffi.Pointer<ffi.Char> ArcName;

  // wchar_t *ArcNameW
  external ffi.Pointer<ffi.Void> ArcNameW;

  @ffi.UnsignedInt()
  external int OpenMode;

  @ffi.UnsignedInt()
  external int OpenResult;

  external ffi.Pointer<ffi.Char> CmtBuf;

  @ffi.UnsignedInt()
  external int CmtBufSize;

  @ffi.UnsignedInt()
  external int CmtSize;

  @ffi.UnsignedInt()
  external int CmtState;

  /// Archive-level flags (ROADF_*). Populated by RAROpenArchiveEx after open.
  @ffi.UnsignedInt()
  external int Flags;

  // UNRARCALLBACK — we set callbacks via RARSetCallback instead
  external ffi.Pointer<ffi.Void> Callback;

  // LPARAM UserData (long = 8 bytes on 64-bit Unix)
  @ffi.Long()
  external int UserData;

  /// Optional flags (ROADOF_*). Set ROADOF_KEEPBROKEN (1) to extract
  /// files even when the archive is damaged.
  @ffi.UnsignedInt()
  external int OpFlags;

  // wchar_t *CmtBufW
  external ffi.Pointer<ffi.Void> CmtBufW;

  // wchar_t *MarkOfTheWeb
  external ffi.Pointer<ffi.Void> MarkOfTheWeb;

  @ffi.Array.multi([23])
  external ffi.Array<ffi.Uint32> Reserved;
}

/// Archive-level metadata returned by [UnrarExtractor.archiveInfo].
class ArchiveInfo {
  const ArchiveInfo({
    required this.isVolume,
    required this.hasComment,
    required this.isSolid,
    required this.hasEncryptedHeaders,
    required this.isFirstVolume,
    required this.isLocked,
    required this.hasSigned,
    required this.hasRecovery,
  });

  /// Archive is part of a multi-volume set.
  final bool isVolume;

  /// Archive contains a comment.
  final bool hasComment;

  /// Archive uses solid compression.
  final bool isSolid;

  /// Archive headers are encrypted (password needed even for listing).
  final bool hasEncryptedHeaders;

  /// This is the first volume in a multi-volume set.
  final bool isFirstVolume;

  /// Archive is locked (protected against modification).
  final bool isLocked;

  /// Archive has an authenticiy verification signature.
  final bool hasSigned;

  /// Archive contains a recovery record.
  final bool hasRecovery;

  factory ArchiveInfo.fromFlags(int flags) => ArchiveInfo(
        isVolume: (flags & b.ROADF_VOLUME) != 0,
        hasComment: (flags & b.ROADF_COMMENT) != 0,
        isSolid: (flags & b.ROADF_SOLID) != 0,
        hasEncryptedHeaders: (flags & b.ROADF_ENCHEADERS) != 0,
        isFirstVolume: (flags & b.ROADF_FIRSTVOLUME) != 0,
        isLocked: (flags & b.ROADF_LOCK) != 0,
        hasSigned: (flags & b.ROADF_SIGNED) != 0,
        hasRecovery: (flags & b.ROADF_RECOVERY) != 0,
      );

  @override
  String toString() => 'ArchiveInfo('
      'isVolume: $isVolume, '
      'isSolid: $isSolid, '
      'hasEncryptedHeaders: $hasEncryptedHeaders, '
      'isFirstVolume: $isFirstVolume)';
}
